# Generated by Django 4.2.7 on 2024-10-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_shipped',
            field=models.DateField(blank=True, null=True),
        ),
    ]
